### ISSUE TITLE
install with laravel 11 php 8.2.*

### ISSUE THREAD

**Issue by medhirajsharma** [haridarshan/laravel-cloudfront-url-signer#10]
Could not find a version of package haridarshan/laravel-url-signer-cloudfront matching your minimum-stability (stab
  le). Require it with an explicit version constraint allowing its desired stability.

**Comment by haridarshan** [comment]
Added Laravel 11
https://github.com/haridarshan/laravel-url-signer-cloudfront/releases/tag/v1.0.0
